### ISSUE TITLE
Gentoo ebuild improvements

### ISSUE THREAD

**Issue by metafarion** [jcorporation/myMPD#288]
Hi, I've been adapting the included Gentoo ebuild to use in my portage overlay, and I had a couple questions about the optional features and dependencies.

1.  Java is listed as a build-time dependency, but is also currently tied to the java USE flag, which can be turned on and off.  However, I had the impression that Java is not optional; myMPD will not compile without it, is that right?

2.  Libid3tag and FLAC are both listed as optional and providing functionality related to embedded album art.  Is this because FLAC is needed to handle album art for .flac files specifically, and libid3tag handles all other file formats?  If FLAC was enabled and libid3tag was not, would there be embedded album art for only .flac files, or is libid3tag needed regardless?

3.  Currently the myMPD ebuild has MPD itself as a dependency, but that's not quite the case is it?  myMPD can be compiled and run on a system that doesn't have MPD can't it?  And then used to control a different system where MPD IS installed?

4.  libmpdclient is listed as a backend for myMPD, but not as a dependency.  Are the sources for libmpdclient included with myMPD so there is no need to have it as a separate dependency?

**Comment by jcorporation** [comment]
1. Java is an optional build dependency, if java is not installed the build scripts falls back to not minify css and js files.
2. libid3tag and flac operates independently.
3. myMPD can be build and run on a system without MPD installed, the dependency is an error.
4. myMPD includes a patched version of libmpdclient, I call it libmympdclient. myMPD has no dependency to an external libmpdclient library.

It would be cool if you share your final ebuild file. I am not familiar with gentoo ebuild.

**Comment by metafarion** [comment]
I'd be glad to.  Though I'm still pretty new at writing ebuilds; itspec-ru  ( #266 )  is probably more proficient than I am, but there were just a couple of changes I wanted to make for my own use.  I'll let you guys decide if you want to actually use them.

**Comment by jcorporation** [comment]
I merged some changes from your ebuild in the v6.5.0 branch. I added also a dependency to lua. myMPD v6.5.0 integrates lua for scripting purposes. But I have no working gentoo installation to test it.

**Comment by metafarion** [comment]
I'm having a little trouble getting 6.5.0 to build with lua enabled. This is what it fails on:
```
Searching for lua
-- Configuring done
-- Generating done
-- Build files have been written to: ~/myMPD-6.5.0/release
[  1%] Building C object CMakeFiles/mympd.dir/src/mympd_api/mympd_api_scripts.c.o
~/myMPD-6.5.0/src/mympd_api/mympd_api_scripts.c: In function ‘mympd_api_script_execute’:
~/myMPD-6.5.0/src/mympd_api/mympd_api_scripts.c:310:61: error: implicit declaration of function ‘luaopen_coroutine’; did you mean ‘luaopen_string’? [-Werror=implicit-function-declaration]
  310 |             else if (strcmp(tokens[i], "coroutine") == 0) { luaopen_coroutine(lua_vm); }
      |                                                             ^~~~~~~~~~~~~~~~~
      |                                                             luaopen_string
~/myMPD-6.5.0/src/mympd_api/mympd_api_scripts.c:310:61: error: nested extern declaration of ‘luaopen_coroutine’ [-Werror=nested-externs]
~/myMPD-6.5.0/src/mympd_api/mympd_api_scripts.c:312:61: error: implicit declaration of function ‘luaopen_utf8’; did you mean ‘luaopen_math’? [-Werror=implicit-function-declaration]
  312 |             else if (strcmp(tokens[i], "utf8") == 0)      { luaopen_utf8(lua_vm); }
      |                                                             ^~~~~~~~~~~~
      |                                                             luaopen_math
~/myMPD-6.5.0/src/mympd_api/mympd_api_scripts.c:312:61: error: nested extern declaration of ‘luaopen_utf8’ [-Werror=nested-externs]
~/myMPD-6.5.0/src/mympd_api/mympd_api_scripts.c:318:61: error: implicit declaration of function ‘luaopen_bit32’; did you mean ‘luaopen_math’? [-Werror=implicit-function-declaration]
  318 |             else if (strcmp(tokens[i], "bit32") == 0)     { luaopen_bit32(lua_vm); }
      |                                                             ^~~~~~~~~~~~~
      |                                                             luaopen_math
~/myMPD-6.5.0/src/mympd_api/mympd_api_scripts.c:318:61: error: nested extern declaration of ‘luaopen_bit32’ [-Werror=nested-externs]
~/myMPD-6.5.0/src/mympd_api/mympd_api_scripts.c:334:14: error: implicit declaration of function ‘luaL_loadfilex’; did you mean ‘luaL_loadfile’? [-Werror=implicit-function-declaration]
  334 |         rc = luaL_loadfilex(lua_vm, script_arg->script_fullpath, "t");
      |              ^~~~~~~~~~~~~~
      |              luaL_loadfile
~/myMPD-6.5.0/src/mympd_api/mympd_api_scripts.c:334:14: error: nested extern declaration of ‘luaL_loadfilex’ [-Werror=nested-externs]
~/myMPD-6.5.0/src/mympd_api/mympd_api_scripts.c: In function ‘lua_err_to_str’:
~/myMPD-6.5.0/src/mympd_api/mympd_api_scripts.c:402:14: error: ‘LUA_ERRGCMM’ undeclared (first use in this function); did you mean ‘LUA_ERRMEM’?
  402 |         case LUA_ERRGCMM:
      |              ^~~~~~~~~~~
      |              LUA_ERRMEM
~/myMPD-6.5.0/src/mympd_api/mympd_api_scripts.c:402:14: note: each undeclared identifier is reported only once for each function it appears in
~/myMPD-6.5.0/src/mympd_api/mympd_api_scripts.c: In function ‘_mympd_api’:
~/myMPD-6.5.0/src/mympd_api/mympd_api_scripts.c:535:22: error: implicit declaration of function ‘lua_isinteger’; did you mean ‘lua_tointeger’? [-Werror=implicit-function-declaration]
  535 |             else if (lua_isinteger(lua_vm, i + 2)) {
      |                      ^~~~~~~~~~~~~
      |                      lua_tointeger
~/myMPD-6.5.0/src/mympd_api/mympd_api_scripts.c:535:22: error: nested extern declaration of ‘lua_isinteger’ [-Werror=nested-externs]
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/mympd.dir/build.make:661: CMakeFiles/mympd.dir/src/mympd_api/mympd_api_scripts.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:98: CMakeFiles/mympd.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

This is with liblua 5.1.5.  It looks like there may be missing libraries here, but I'm not at all familiar with lua so I'm not sure what they might be.

**Comment by metafarion** [comment]
Actually, after a little more research, I see now that Lua 5.1 is quite old. For some reason newer versions are masked in the Gentoo main repository.  Do you know what the minimum required version is here?

**Comment by jcorporation** [comment]
You need Lua 5.3. I updated the CMakeLists.txt in devel and the documentation accordingly.

**Comment by metafarion** [comment]
Cool, I'll get to work on that.  Also it might be a good idea to prevent build.sh from continuing with an insufficient version of lua.  Right now for me, it just detects 1.5.1, keeps going, and then fails out later.

**Comment by metafarion** [comment]
Ok, I think I'm satisfied with this thing now.  I've built and tested it with various options in x86 and x86_64, though I don't have the means to do so with ARM.

https://gist.github.com/metafarion/7681363ab4b849f8279644da472379d7

My changes:

- Fixed the USE flags and ENABLE_ environmental variables so they are no longer ignored by the build script.
- Disabled Lua by default because the Gentoo repositories have masked all versions newer than 5.1.  Building with Lua is possible, but it requires a bit of hand-tuning on the part of the user and I wanted the default build to work out-of-the-box.
- Leaving Java as an optional dependency, not pulled in by default unless it is enabled systemwide or explicitly by the user.  It's a hefty dependency that enables very non-critical functionality, and people often try to avoid installing such dependencies on lightweight or headless systems.
- Also leaving SSL on/off up to the user's system, as enabling it creates additional work to do regarding certificate trust.  Also because it seems to me that myMPD is most likely to be used within a LAN, where encryption and trust aren't so important.
- mympd user and group are now added at the end of the install instead of the beginning to avoid altering the system before the install is successful.  Also added some logic to check if the user and group already exist.
- Install will now be halted if build process doesn't exit with code 0.
- Added Gentoo-specific handling for pre-stripped binaries.
- Minor re-wording of package description and elog output.

**Comment by jcorporation** [comment]
I merged some changes from your ebuild back into my ebuild file. 

> Added Gentoo-specific handling for pre-stripped binaries.

If lua is enabled there was an additional binary: mympd-script

**Comment by metafarion** [comment]
> If lua is enabled there was an additional binary: mympd-script

Ahh, that's a good point, I'll have to include that.

One other thing I wanted to point out after looking at the merged ebuild: When referring to Gentoo packages, if you are specifying a version, you need an operator before the category and name.
For example:
`dev-lang/lua` is correct (version unspecified)
and `>=dev-lang/lua-5.3` is also correct (greater than or equal to lua 5.3)
but `dev-lang/lua-5.3` is an incomplete statement will not parse correctly when building

**Comment by jcorporation** [comment]
Thanks for review, I will fix it.

**Comment by metafarion** [comment]
Oh, you know what else just occurred to me; since there's another binary, we need another dobin statement in src_install()
And since it's conditional on the lua USE flag, it should probably look something like this:

`if use lua; then`
`dobin cli_tools/mympd-script`
`fi`

**Comment by jcorporation** [comment]
this makes sense ... Gentoo ebuilds are really complex...

**Comment by metafarion** [comment]
They certainly can be.  I'm learning mostly by copying other ebuilds.
